name: CI/CD_SpringBoot_Deploy

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t <YOUR_DOCKER_USERNAME>/<IMAGE_NAME>:latest .

      - name: Push Docker Image
        run: docker push <YOUR_DOCKER_USERNAME>/<IMAGE_NAME>:latest


  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: docker pull <YOUR_DOCKER_USERNAME>/<IMAGE_NAME>:latest

      - name: Stop Old Container
        run: docker rm -f springboot_app || true

      - name: Start New Spring Boot Container
        run: |
          docker run -d \
          --name springboot_app \
          -p 8080:8080 \
          <YOUR_DOCKER_USERNAME>/<IMAGE_NAME>:latest
